### ISSUE TITLE
Does not work with monorepos using Yarn workspaces

### ISSUE THREAD

**Issue by adrianmcli** [alex-wilmer/prettieslint#4]
I got this error while trying to run `npx prettieslint` on my Lerna monorepo w/ Yarn workspaces.

```
(node:96420) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add -D babel-eslint eslint eslint-config-prettier eslint-plugin-babel eslint-plugin-prettier prettier
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
```

Might want to give an option/flag for people wanting to use this for monorepos w/ Yarn workspaces.

**Comment by adrianmcli** [comment]
Alternatively, it might make sense for prettieslint to detect the lerna.json to know that it's in a monorepo that uses Yarn workspaces and adjust the command accordingly.

**Comment by alex-wilmer** [comment]
I have thought about this actually. Most of my projects are yarn workspaces and the inner modules have their own eslint configs that require the root one and do any modifications if necessary. It seems necessary to prevent editor linters  from getting confused. 

example:

```
packages/
  moduleA/
    .eslintrc.js
.eslintrc.js
```

where the inner one looks like

```
module.exports = require('../../.eslintrc')
````

it would be very nice if this pacakge generated those files as well
