### ISSUE TITLE
Use a default .prettierrc

### ISSUE THREAD

**Issue by 0xrohan10** [alex-wilmer/prettieslint#6]
Eventually will allow users to customize prettier styles, by using a prettierrc instead of hardcoding the values within `index.js`

**Comment by alex-wilmer** [comment]
the prettier options are in the generated eslint config. that's kind of the point

**Comment by 0xrohan10** [comment]
What if I want my eslint config built off my prettierrc?

**Comment by adrianmcli** [comment]
@rohannair that's quite the custom use-case no?

I think this library is targeting a project that does not currently have prettier or eslint setup.
